#+title: build.el
#+description: Build your projects directly in Emacs, without hassle

This package strives to provide clean and easy to understand
functions, as well as a transient menu, to build projects of various
build systems.


* Features
Supported build systems:

+ Bazel
+ Make
+ CMake
+ Cargo
+ Meson + Ninja
+ NPM

* Usage

build.el provides interactive build commands for each build system.
Build commands are prefixed by the name of the build system:

| Build system | Prefix                     |
|--------------+----------------------------|
| CMake        | build-cmake-               |
| Bazel        | build-bazel-               |
| Make         | build-make-                |
| Cargo        | build-cargo-               |
| Meson+Ninja  | build-meson-, build-ninja- |
| NPM          | build-npm-                 |

Each build system exposes different amounts of functions, depending on
the capability of the build system.

Though in general, where-ever possible, build.el will try to
auto-complete possible targets given the context for you.

~Make~, only has ~build-make-run~, which will prompt you for a target that
should be ran, the targets are auto-completed from the Makefile itself.

~Bazel~, on the other hand, has ~build-bazel-run~, ~build-bazel-test~, and
~build-bazel-build~.  Running any of the commands will trigger a
~completing-read~ auto suggestion with matching targets.


~CMake~ has ~build-cmake-build~ and ~build-cmake-generate~.

~Meson~ has ~build-meson-setup~, compilation is done via ~build-ninja-build~.

~NPM~ has ~build-npm-run~, ~build-npm-install~ and ~build-npm-uninstall~.
~run~, and ~uninstall~ will be autocompleted from the ~package.json~ in the project root.

In general, each build system has it's own transient menu, these are always
called ~build-<system>-transient~.  Though you will probably want to use
~build-menu~, which will try to infer the build system of the current
project and show that instead.

* Demo

#+html: <img style="width: 50%" src="https://github.com/user-attachments/assets/4fd17387-24af-47a2-92a1-2cf7065c73eb" />
#+html: <img style="width: 50%" src="https://github.com/user-attachments/assets/9f4a4a7b-c925-4e3d-9acb-45c833a7c7ab" />
#+html: <img style="width: 50%" src="https://github.com/user-attachments/assets/86409bc6-274e-493a-8950-f880d8bf4822" />
#+html: <img style="width: 50%" src="https://github.com/user-attachments/assets/5de4ec37-6334-4788-9bc8-92cf06666c91" />
#+html: <img style="width: 50%" src="https://github.com/user-attachments/assets/08e9c25a-d1f9-4115-b7f7-cf70fc1b8b21" />
#+html: <img style="width: 50%" src="https://github.com/user-attachments/assets/bd46f6eb-6c67-42a8-89da-853b710547b5" />

* Installation

** Manually
Clone the repository:
#+BEGIN_SRC bash
 git clone https://github.com/27justin/build.el ~/.emacs.d/site-lisp/build.el
#+END_SRC

Add it to your load path

#+BEGIN_SRC elisp
  (add-to-list 'load-path "~/.emacs.d/site-lisp/build.el")
  (use-package build)
#+END_SRC

Done.
